steps:
  # 1. Cloud Functions (第2世代) をデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - run-yamap-auto-domo-function # Cloud Function 名 (任意)
      - --gen2
      - --region=asia-northeast1
      - --runtime=python310 # Dockerfile を使用する場合でもベースランタイムを指定
      - --source=. # ビルドコンテキストを現在のディレクトリに設定
      - --entry-point=run_yamap_auto_domo_function # main.py の関数名
      - --trigger-http
      - --allow-unauthenticated # Schedulerからの呼び出しのため (本番環境ではOIDC認証を強く推奨)
      - --max-instances=1 # Selenium処理のためインスタンス数を制限
      - --timeout=540s # 9分 (Selenium処理は時間がかかる可能性)
      - --cpu=1
      - --memory=2Gi # Headless Chrome はメモリを消費するため
      # 環境変数はSecret Manager経由で設定
      - --set-secrets=YAMAP_LOGIN_ID=gcp-secret-yamap-id:latest,YAMAP_LOGIN_PASSWORD=gcp-secret-yamap-password:latest,YAMAP_USER_ID=gcp-secret-yamap-user-id:latest
      # 使用する設定ファイルを環境変数で指定
      - --update-env-vars=YAMAP_CONFIG_FILE=yamap_auto/config.yaml

options:
  logging: CLOUD_LOGGING_ONLY
