steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/selenium-batch-job', '.' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - selenium-batch-job
      - --image=gcr.io/$PROJECT_ID/selenium-batch-job
      - --region=asia-northeast1
      - --platform=managed
      - --memory=1Gi
      - --timeout=300
      - --no-allow-unauthenticated
      - --set-secrets=_YAMAP_LOGIN_ID=gcp-secret-yamap-id:latest,_YAMAP_LOGIN_PASSWORD=gcp-secret-yamap-password:latest
options:
  logging: CLOUD_LOGGING_ONLY
