steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/yamap-auto-domo-follow', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/yamap-auto-domo-follow' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - jobs
      - deploy
      - yamap-auto-domo-follow
      - --image=gcr.io/$PROJECT_ID/yamap-auto-domo-follow
      - --region=asia-northeast1
      - --set-secrets=_YAMAP_LOGIN_ID=gcp-secret-yamap-id:latest,_YAMAP_LOGIN_PASSWORD=gcp-secret-yamap-password:latest
      - --memory=1Gi
      - --task-timeout=900s
      - --max-retries=1
      - --command=python
      - --args=-m,yamap_auto.yamap_auto_domo

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - gcr.io/$PROJECT_ID/yamap-auto-domo-follow
